// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopBridgeApi.Context;

namespace ShopBridgeApi.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20211022222253_CreateNewTableProduct")]
    partial class CreateNewTableProduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShopBridgeApi.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Company");

                    b.Property<DateTime>("DateSold");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new { Id = 1, Company = "Sunfeast", DateSold = new DateTime(2021, 10, 14, 10, 14, 30, 0, DateTimeKind.Unspecified), Description = "Chocolate filled Cookies", Name = "Dark fantasy", Price = 30m },
                        new { Id = 2, Company = "Lays", DateSold = new DateTime(2021, 10, 15, 10, 14, 30, 0, DateTimeKind.Unspecified), Description = "Fried Chips flavoured with indian spices", Name = "Lays Indian Masala", Price = 10m },
                        new { Id = 3, Company = "Sunfeast", DateSold = new DateTime(2021, 10, 14, 10, 14, 30, 0, DateTimeKind.Unspecified), Description = "Chocolate filled Cookies", Name = "Hair Dryer", Price = 30m }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
